spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  cache:
    cache-names: restaurants, users, dishes, menus
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=60s

  mvc:
    log-request-details: true

logging:
  level:
    root: WARN
    top.fedoseev.restaurant.voting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

app:
  votingTillTime: "11:00"
